warpem/warp

- WarpLib/Tools/Matrix3.cs
...with correct understanding of mat3 layout in Warp
first part of #18 
tests done:
In Python two different libraries, one implemented by me, agree:
```python
import numpy as np
from scipy.spatial.transform import Rotation as R
from eulerangles.math import matrix2xyz_extrinsic
M = np.array([[  -0.459981, -0.86181512,   0.2137573],
[-0.27488282, -0.09069872, -0.95719025],
[ 0.84430854, -0.49904753, -0.19517849]]) 
eulers = R.from_matrix(M).as_euler(seq='xyz', degrees=True)
print(eulers)
eulers2 = matrix2xyz_extrinsic(rotation_matrices=M) print(eulers2)   
```
In C#:
```C#
float m11, m21, m31, m12, m22, m32, m13, m23, m33; 
m11 = -0.459981f; 
m21 = -0.27488282f; 
m31 = 0.84430854f; 
m12 = -0.86181512f; 
m22 = -0.09069872f; 
m32 = -0.49904753f; 
m13 = 0.2137573f; 
m23 = -0.95719025f; 
m33 = …
```
> Reimplement EulerXYZExtrinsicFromMatrix 

- WarpTools/Commands/Tiltseries/EvaluateModelTiltseries.cs
As discussed in https://github.com/cryo-et-standards/projection-model/issues/1
> Added ts_eval_model tool to allow evaluation of a tilt series' projection / deformation model at a set of positions

- WarpTools/Commands/Tiltseries/ExportParticlesTiltseries.cs
> enable nullable in tilt series export to avoid compilation warnings

- WarpTools/Commands/Tiltseries/ExportParticlesTiltseries.cs
> Add more debug output to particle export

- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
> add warning in tilt series quick start guide about mrc16b output

- WarpLib/Image.cs
- docs/reference/warptools/environment_variables.md
- mkdocs.yml
also added some docs for any env vars we add
cc @dtegunov so you're aware
> Add option to write 32 bit MRC files by setting an environment variable

- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
> update docs to reflect environment variable for forcing 32 bit output

- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
- scripts/EMPIAR-10491_5TS_e2e.sh
> invert tilt angles on import in ts processing example

- docs/reference/warptools/subsets.md
- mkdocs.yml
> add docs describing subset selection mechanisms in WarpTools

- docs/reference/boxnet/fs_training.md
- mkdocs.yml
> add docs for frame series boxnet training

- docs/reference/warptools/custom_tilt_series_alignments.md
- mkdocs.yml
this PR adds docs for how to run tilt series alignment outside the confines of the IMOD/AreTomo2 warppers we provide
> add docs for custom TSA workflows

- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
> update defocus handedness docs after adding `--dont_invert` to `ts_import`

- WarpTools/Commands/Tiltseries/ImportTiltseries.cs
Reverts warpem/warp#102
need to investigate but think this is 90 degrees off based on tests with EMPIAR-10499
> Revert "Add tilt axis check during `ts_import`"

- Warp.sln
- WarpTools/Commands/Tiltseries/ImportTiltseries.cs
I was calculating the vector for the tilt axis angle as if the angle was the angle between the x axis and the tilt axis - we parametrise it as the angle with the Y-axis
> re-add tilt axis angle check on `ts_import`

- scripts/build-native-unix.sh
configures number of jobs passed to make
> add -j option to build-native-unix.sh

- WarpLib/Sociology/Species.cs
- WarpLib/TiltSeries.cs
> remove debug outputs from M

- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
> remove newer wget options

- WarpTools/Commands/CreateSettings.cs
> don't error when creating settings for tomostar files which don't exist yet

- docs/reference/warptools/processing_tilt_series_stacks.md
- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
- mkdocs.yml
c.f. #119 
cc @uermel this might be of interest
> Add documentation explaining how to process tilt series stacks

- WarpTools/Commands/Tiltseries/ImportTiltseries.cs
need to check this in more detail c.f. #131
> comment out tilt axis angle estimation during ts_import

- WarpLib/TiltSeries.cs
> parse wrpAngleTilt and wrpDose without respecting locale

- WarpLib/TiltSeries.cs
> add missing invariant culture spec in float parsing

- WarpTools/Commands/CreateSettings.cs
> Warn if tomogram dimensions appear small

- WarpLib/Movie.cs
- WarpTools/Commands/BaseCommand.cs
> Fail loudly if frequency range badly set

- WarpTools/Commands/Tiltseries/ImportTiltseries.cs
> reinstate average intensity calculation

- docs/reference/warptools/api/frame_series.md
- docs/reference/warptools/api/general.md
- docs/reference/warptools/api/tilt_series.md
- mkdocs.yml
- scripts/generate-warptools-api-docs.py
script to autogenerate requires WarpTools on the PATH and must be updated with any new commands
> Add API docs for WarpTools CLI's

- docs/reference/warptools/custom_tilt_series_alignments.md
> add missing reference to ts_import_alignments

- WarpLib/Tools/FloatVectors.cs
- WarpTools/Commands/Tiltseries/ExportParticlesTiltseries.cs
no support for centered coords (yet?)
took the opportunity to tidy up the program a bit
closes #176
> add support for particle export from RELION 5 style STAR files

- .github/workflows/ci.yml
- README.md
- conda-recipe/meta.yaml
- docs/user_guide/warptools/installation.md
- warp_build.yml
- warp_build_windows.yml
> bump to cu118

- WarpLib/Tools/Helper.cs
- WarpTools/Commands/Tiltseries/AreTomoTiltseries.cs
- WarpTools/Commands/Tiltseries/EtomoFiducialsTiltseries.cs
- WarpTools/Commands/Tiltseries/EtomoPatchTrackTiltseries.cs
> Add checks for executables on PATH for tilt series alignment wrappers

- WarpTools/Commands/General/ThresholdPicks.cs
> add particle number output to threshold_picks

- WarpTools/Commands/Tiltseries/EtomoFiducialsTiltseries.cs
> add exception if fiducial size not passed to etomo fiducials CLI

- WarpLib/TiltSeries.cs
> change xf -> tlt in no tlt found error message

- WarpLib/TiltSeries.cs
- WarpTools/Commands/Tiltseries/EtomoFiducialsTiltseries.cs
- WarpWorker/WarpWorker.cs
closes #211
needs testing before merging
> make target number of beads configurable in etomo fiducials wrapper

- MTools/Commands/CreateSpecies.cs
> add warning if pixel sizes don't match during species creation in M

- docs/reference/mtools/api/mcore.md
- docs/reference/mtools/api/mtools.md
- docs/reference/warptools/api/frame_series.md
- docs/reference/warptools/api/general.md
- docs/reference/warptools/api/tilt_series.md
- scripts/generate-mtools-api-docs.py
> Add MTools/MCore API docs

- docs/user_guide/warptools/quick_start_warptools_tilt_series.md
> Add note about spectrum whitening in template matching to TS user guide

- WarpTools/Commands/Tiltseries/ExportParticlesTiltseries.cs
> add --max_missing_tilts option to particle series export

- WarpLib/Tools/VirtualConsole.cs
> Fix negative count bug in VirtualConsole

- WarpTools/Commands/BaseCommand.cs
tested and working with both fs and ts commands
> Write out processed_items.json from WarpTools commands

- WarpLib/Movie.cs
> add motion track JSON export to Movie.cs

- WarpLib/Movie.cs
> create directory before writing motion tracks JSON file

- WarpLib/Movie.cs
fix for bug introduced in #305
> path -> IOPath

- WarpTools/Commands/General/ThresholdPicks.cs
- WarpTools/Commands/Tiltseries/TemplateMatchTiltseries.cs
> fix data flow when both input and output processing directories are set in threshold_picks

- WarpLib/Movie.cs
- WarpLib/OptionsWarp.cs
- WarpLib/WorkerWrapper.cs
- WarpTools/Commands/BaseCommand.cs
- WarpTools/Commands/Frameseries/BoxNetInferFrameseries.cs
- WarpTools/Commands/Frameseries/CTFFrameseries.cs
- WarpTools/Commands/Frameseries/ExportMicrographsFrameseries.cs
- WarpTools/Commands/Frameseries/ExportParticlesFrameseries.cs
- WarpTools/Commands/Frameseries/MotionCTFFrameseries.cs
- WarpTools/Commands/Frameseries/MotionFrameseries.cs
- WarpTools/Commands/Frameseries/TardisSegmentMembranesFrameseries.cs
- WarpTools/Commands/Tiltseries/AreTomoTiltseries.cs
- WarpTools/Commands/Tiltseries/CTFTiltseries.cs
- WarpTools/Commands/Tiltseries/EtomoFiducialsTiltseries.cs
- WarpTools/Commands/Tiltseries/EtomoPatchTrackTiltseries.cs
- WarpTools/Commands/Tiltseries/ExportParticlesTiltseries.cs
- WarpTools/Commands/Tiltseries/ReconstructTiltseries.cs
- WarpTools/Commands/Tiltseries/StackTiltseries.cs
- WarpTools/Commands/Tiltseries/TemplateMatchTiltseries.cs
- WarpWorker/WarpWorker.cs
`WarpTools fs_tardis_segment_membranes`
> add WarpTool for 2D membrane segmentation with tardis

- docs/reference/warptools/tomogram_particle_files.md
c.f. https://forum.image.sc/t/how-to-extract-particles-from-warp-2-0-tomograms-that-were-picked-using-external-programs/109659
> add basic description of RELION 3.0 tomogram particle STAR files to docs

- docs/reference/warptools/processing_warp_v1_data.md
- mkdocs.yml
> Add docs for 1.x -> 2.x transition for tilt series processing

- WarpTools/Commands/Tiltseries/ImportTiltseries.cs
c.f. #369 #338 
This should at least provoke users to think about this a little more...
> write out warning about automatically determined tilt axis angle by default
